apiVersion: kubernetes-create.io/v1
kind: Cluster
metadata:
  name: aws-rke2-cluster

spec:
  providers:
    aws:
      enabled: true
      region: us-east-1
      # Credentials via environment variables:
      # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN
      vpc:
        create: true
        cidr: 10.0.0.0/16

  network:
    cidr: 10.0.0.0/16
    podCidr: 10.244.0.0/16
    serviceCidr: 10.96.0.0/12
    wireguard:
      enabled: true
      serverEndpoint: ""  # Auto-detected from first master
      meshNetworking: true

  kubernetes:
    distribution: rke2
    version: v1.28.5+rke2r1
    networkPlugin: calico
    clusterDns: 10.96.0.10
    clusterDomain: cluster.local
    rke2:
      channel: stable
      tlsSan:
        - "*.amazonaws.com"
      disableComponents:
        - rke2-ingress-nginx  # We'll use our own ingress
      secretsEncryption: true
      snapshotScheduleCron: "0 */6 * * *"  # Every 6 hours
      snapshotRetention: 10

  nodePools:
    # 3 Master nodes for HA
    - name: masters
      provider: aws
      count: 3
      roles:
        - master
        - etcd
      size: t3.medium
      region: us-east-1

    # 3 Worker nodes
    - name: workers
      provider: aws
      count: 3
      roles:
        - worker
      size: t3.large
      region: us-east-1
      # spotInstance: true      # Uncomment to use Spot Instances
      # spotMaxPrice: "0.05"    # Max price per hour

  ssh:
    keyPath: ~/.ssh/id_rsa
    publicKeyPath: ~/.ssh/id_rsa.pub
    port: 22

  addons:
    argocd:
      enabled: true
      namespace: argocd
    monitoring:
      enabled: true
      namespace: monitoring
